services:
  - type: web
    name: config-service
    env: docker
    dockerContext: .
    dockerfilePath: ConfigService/Dockerfile
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SCRAPPER_SERVICE_URL
        value: http://scrapper-service:10000
      - key: VECTOR_SERVICE_URL
        value: http://vector-service:10000

  - type: web
    name: scrapper-service
    env: docker
    dockerContext: .
    dockerfilePath: ScrapperService/Dockerfile
    plan: free
    envVars:
      - key: CONFIG_SERVICE_URL
        value: http://config-service:10000

  - type: web
    name: vector-service
    env: docker
    dockerContext: .
    dockerfilePath: VectorService/Dockerfile
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: BUCKET_NAME
        sync: false