server:
  port: ${PORT:8081}

spring:
  application:
    name: ConfigService
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

supabase:
  url: ${SUPABASE_URL:}
  key: ${SUPABASE_KEY:}
  bucket: ${BUCKET_NAME:config-files}

scrapper-service:
  url: ${SCRAPPER_SERVICE_URL:http://scrapper-service:8082}

vector-service:
  url: ${VECTOR_SERVICE_URL:http://vector-service:8083}